#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/sm8650-common

PRODUCT_COPY_FILES += \
    vendor/samsung/sm8650-common/proprietary/product/etc/permissions/UimService.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/UimService.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio/sku_pineapple/audio_effects.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_pineapple/audio_effects.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio/sku_pineapple/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_pineapple/audio_effects.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_effects_haptic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_haptic.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_effects_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_sec.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_effects_spatializer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_spatializer.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/batching.conf:$(TARGET_COPY_OUT_VENDOR)/etc/batching.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/charger_fw_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fw_fstab.qti \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/clstc_config_library.xml:$(TARGET_COPY_OUT_VENDOR)/etc/clstc_config_library.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/data/nicm_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/nicm_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/data/tlpd_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/tlpd_oem_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/dax3_media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dax3_media_codecs_dolby_audio.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/display/DPU10__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU10__.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/display/DPU9__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU9__.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/display/advanced_sf_offsets.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/advanced_sf_offsets.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/floating_feature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/floating_feature.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/gnss_antenna_info.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gnss_antenna_info.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.gatekeeper-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.gnss-aidl-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-aidl-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service-spu-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service-spu-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/hermesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hermesd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/hw/init.qti.kernel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.qti.kernel.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.audio.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.audio.samsung.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.qccvendor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qccvendor.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.qti.media.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.media.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.qti.qcv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.qcv.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.spdaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.spdaemon.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.vendor.onebinary.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.onebinary.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/loc-launcher.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/loc-launcher.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qms.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qms.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qwesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qwesd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/shsusrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/shsusrd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/ssgtzd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ssgtzd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/tlpd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tlpd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/trusteduilistener.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trusteduilistener.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.diag.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.display.color-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.display.color-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.iop@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.iop@2.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.perf2-hal-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf2-hal-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.secureprocessor@1.0.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.secureprocessor@1.0.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.trustedui-aidl-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.trustedui-aidl-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.trustedui@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.trustedui@1.0-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.smp2p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.smp2p.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.samsung.rilchip.qcom.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rilchip.qcom.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.samsung.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rild.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.sensors.sscrpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.sscrpcd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/locale/plmn_delta_eng.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_eng.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/locale/plmn_delta_zh-rCN.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rCN.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/locale/plmn_delta_zh-rHK.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rHK.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/locale/plmn_delta_zh-rTW.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rTW.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/mem_logger_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mem_logger_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/models/acd/environment.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/environment.eai \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/models/acd/event.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/event.eai \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/models/acd/music.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/music.eai \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/models/acd/speech.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/speech.eai \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/mtu-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtu-conf.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/pdpcnt-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pdpcnt-conf.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/perf/avcsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/avcsysnodesconfigs.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/perf/commonsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonsysnodesconfigs.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/perf/targetavcsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetavcsysnodesconfigs.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/perf/targetsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetsysnodesconfigs.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/perf/testcommonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/testcommonresourceconfigs.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/perf/testtargetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/testtargetresourceconfigs.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta_hktw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_hktw.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta_ltn.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_ltn.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/pwr/PSMPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/PSMPowerOptFeature.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/qms_log_config:$(TARGET_COPY_OUT_VENDOR)/etc/qms_log_config \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sec_config_oem:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config_oem \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/atfwd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/atfwd@2.0.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-base.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-edgnss-daemon.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-edgnss-daemon.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-qsap-location.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-qsap-location.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/qms.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qms.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/qti-systemd.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qti-systemd.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/qwesd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qwesd@2.0.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_default_sensors.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_dynamic_sensors.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_dynamic_sensors_template.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_dynamic_sensors_template.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_irq.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_power_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_qrd_tmd2755_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_qrd_tmd2755_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_qsh_ble_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_qsh_ble_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_ble.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_ble.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_camera_common.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_common.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_4.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_4.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_6.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_6.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_6_actuator.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_6_actuator.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/snapdragon_color_libs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/snapdragon_color_libs_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/wifi/indoorchannel.info:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/indoorchannel.info \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/wifi/kiwi_v2/WCNSS_qcom_cfg.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/kiwi_v2/WCNSS_qcom_cfg.ini \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/xtwifi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/xtwifi.conf

PRODUCT_PACKAGES += \
    btaudio_offload_if \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libVkLayer_ADRENO_qprofiler \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.bluetooth@1.1-impl-qti \
    android.hardware.gnss-aidl-impl-qti \
    audio.primary.pineapple \
    gatekeeper.mdfpp \
    libspuqtigatekeeper \
    vendor.qti.hardware.bttpi-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.samsung.hardware.gnss-aidl-impl-sec \
    vulkan.adreno \
    libAlacSwDec \
    libApeSwDec \
    libCB \
    libEvrcSwCodec \
    libFlacSwDec \
    libGPMTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libOpenCL \
    libOpenCL_adreno \
    libPeripheralStateUtils \
    libQSEEComAPI \
    libTouchInputVM \
    libTrustedInput \
    libTrustedInputAIDL \
    libTrustedInputTZ \
    libTrustedInputUtils \
    libTrustedUI \
    libTrustedUIAIDL \
    libTrustedUITZ \
    libTrustedUIVM \
    libVendorSemDataProps \
    libVendorSemTelephonyProps \
    libVoiceSdk \
    lib_SamsungRec_08020 \
    lib_lvacfs \
    libadm \
    libadreno_app_profiles \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libagm \
    libar-pal \
    libarmemlog \
    libaudio_log_utils \
    libaudiofeaturestats \
    libbatching \
    libbluetooth_audio_session_aidl_qti \
    libbluetooth_audio_session_qti \
    libbluetooth_audio_session_qti_2_1 \
    libbt-hidlclient \
    libbtnv \
    libcdfw \
    libcdsp_default_listener \
    libcdsprpc \
    libclstc_algorithm_adapter \
    libclstc_gcp_adapter \
    libclstc_tm \
    libconfigdb \
    libcpion \
    libdataitems \
    libdiag \
    libdigital-dimming \
    libdisp-aba \
    libdisplayconfig.qti \
    libdisplaydebug \
    libdisplayqos \
    libdisplayskuutils \
    libdpp_manager \
    libdpps \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libdsutils \
    libegis_fp_normal_sensor_test \
    libengmode_client \
    libese-grdg \
    libfloatingfeature \
    libgame_enhance \
    libgeofencing \
    libgf_in_system_lib \
    libgnss \
    libgnsspps \
    libgps.utils \
    libgpt \
    libgpudataproducer \
    libgsl \
    libhdr_tm \
    libhdradaptivecustom \
    libhdrdynamic \
    libhdrdynamicootf \
    libhermes \
    libhermes_bdbridge \
    libhermes_cred \
    libhwvault \
    libidl \
    libintervmipc \
    libizat_client_api \
    libizat_core \
    libkcl \
    libkernelmanager \
    liblbs_core \
    liblearningmodule \
    liblistensoundmodel2vendor \
    libllvm-glnext \
    libllvm-qcom \
    libllvm-qgl \
    libloadalgo_stub \
    libloc_api_v02 \
    libloc_api_wds \
    libloc_base_util \
    libloc_core \
    libloc_mq_client \
    libloc_socket \
    libloc_util \
    liblocation_api \
    liblocation_api_msg \
    liblocation_client_api \
    liblocation_integration_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_common \
    liblowi_wifihal \
    libmdmdetect \
    libmdsprpc \
    libmemutils \
    libmeters \
    libminkdescriptor \
    libminksocket_vendor \
    libmm-hdcpmgr \
    libnanopb \
    libnicm \
    libnicm_dsi \
    libnicm_utils \
    libops \
    libpal_net_if \
    libpdmapper \
    libpdnotifier \
    libperfconfig \
    libperfgluelayer \
    libperfioctl \
    libperipheral_client \
    libprofileparamstorage \
    libprotobuf-cpp-full-21.7 \
    libprotobuf-cpp-lite-21.7 \
    libq-perflog \
    libqcbor \
    libqcc_file_agent \
    libqcc_sdk \
    libqcci_legacy \
    libqcmaputils \
    libqdcm-algo \
    libqdcm-json-mode-parser \
    libqdcm-mode-parser \
    libqdi \
    libqdutils \
    libqesdk2_0 \
    libqfp_sensortest \
    libqisl \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_csvt_srvc \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libqrtr \
    libqrtrclient \
    libqseed3 \
    libqsh \
    libqsocket \
    libqspm-mem-utils-vendor \
    libqti-perfd-client \
    libqti-perfd \
    libqti-util \
    libqtigefar \
    librecordalive \
    libril_sem \
    librpmb \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsec-ril \
    libsec_esek \
    libsec_semHalTlc \
    libsec_semRil \
    libsecaudioinfo \
    libsecaudiolevel \
    libsecnativefeature \
    libsecril-client \
    libsehbluetooth_audio_session_aidl \
    libsemnativecarrierfeature \
    libsensorslog \
    libsfp_sensor \
    libsfp_teegw \
    libshctrl \
    libshsc \
    libsi \
    libskeymint10device \
    libskeymint_cli \
    libsnapdragoncolor-manager \
    libsnapdragoncolor-qdcm \
    libsns_api \
    libsns_direct_channel_stub \
    libsnsapi \
    libsnsdiaglog \
    libsnsutils \
    libsoc_helper \
    libspatializerparamstorage \
    libspcom \
    libspeakercalibration \
    libspictrl \
    libspl \
    libspukeymint \
    libspukeymintdeviceutils \
    libspukeymintutils \
    libssd \
    libsubsystem_control \
    libsynaFpSensorTestNwd \
    libsynergy_loc_api \
    libsys_info_cache \
    libsysmon_cdsp_skel \
    libtaautoload \
    libtensorflowlite_c \
    libtestutils \
    libthermalclient \
    libtime_genoff \
    libtinyxml2_1 \
    libtlpd \
    libtlpd_configmgr \
    libtlpd_crypto \
    libtlpd_internal \
    libtlpd_logger \
    libtrustedapploader \
    libubwcp \
    libvkmanager_vendor \
    libvmfilexfer \
    libvmmem \
    libvui_dmgr \
    libvui_dmgr_client \
    libvui_intf \
    libwifiobserver \
    libxml \
    libxtadapter \
    libSnpeHtpV75Skel \
    libapn_dsp_skel \
    libbitml_nsp_75na_skel \
    libdpp_engine_skel \
    libdspCV_skel \
    libdsphist_qc_skel \
    libdspmc_qc_skel \
    libevadsp \
    libfastcvadsp \
    libfastcvdsp_skel \
    libhdr_skel \
    libqsegnetengine_dsp_skel \
    libscveT2T_skel \
    libworker_pool \
    libQnnHtpV75Skel \
    sensors.flicker \
    sensors.grip \
    sensors.qsh \
    libQnnHtp \
    libQnnHtpV75Stub \
    libQnnSystem \
    libasphere \
    libquasar \
    libshoebox \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.qti.diaghal@1.0_vendor \
    vendor.qti.gnss-V5-ndk \
    vendor.qti.gnss-service \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.bttpi-V3-ndk \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.iop@1.0 \
    vendor.qti.hardware.iop@2.0 \
    vendor.qti.hardware.pal@1.0-impl \
    vendor.qti.hardware.perf2-V1-ndk \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qccsyshal@1.1 \
    vendor.qti.hardware.qccsyshal@1.2 \
    vendor.qti.hardware.qseecom-V1-ndk \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.atfwd-V1-ndk \
    vendor.qti.hardware.secureprocessor.common@1.0-helper \
    vendor.qti.hardware.secureprocessor.common@1.0 \
    vendor.qti.hardware.secureprocessor.config@1.0 \
    vendor.qti.hardware.secureprocessor.device@1.0 \
    vendor.qti.hardware.trustedui-V1-ndk \
    vendor.qti.hardware.trustedui@1.0 \
    vendor.qti.hardware.trustedui@1.1 \
    vendor.qti.hardware.trustedui@1.2 \
    vendor.qti.memory.pasrmanager-V1-ndk \
    vendor.qti.memory.pasrmanager@1.0 \
    vendor.qti.power.pasrmanager@1.0 \
    vendor.qti.qccvndhal_aidl-V1-ndk \
    vendor.qti.qccvndhal_aidl-halimpl \
    vendor.qti.qesdhal@1.0 \
    vendor.qti.qesdhal@1.1 \
    vendor.qti.qesdhal@1.2 \
    vendor.qti.qesdhal@1.3 \
    vendor.qti.qspmhal-V1-ndk \
    vendor.samsung.hardware.biometrics.fingerprint-V1-ndk \
    vendor.samsung.hardware.bluetooth.audio-V2-ndk \
    vendor.samsung.hardware.bluetooth@2.0 \
    vendor.samsung.hardware.gnss-V2-ndk_platform \
    vendor.samsung.hardware.hyper-V2-ndk \
    vendor.samsung.hardware.keymint-V3-ndk \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.channel-V1-ndk \
    vendor.samsung.hardware.radio.data-V1-ndk \
    vendor.samsung.hardware.radio.messaging-V1-ndk \
    vendor.samsung.hardware.radio.sim-V1-ndk \
    vendor.samsung.hardware.security.drk-V1-ndk \
    vendor.samsung.hardware.security.drk@2.0 \
    vendor.samsung.hardware.security.hermes-V1-ndk \
    libdsp_streamer_binning \
    libhme_dsp_skel \
    TimeService \
    uimservicelibrary \
    android.hardware.gnss-aidl-service-qti.xml \
    atfwd-saidl.xml \
    bttpi-saidl.xml \
    manifest_non_qmaa.xml \
    manifest_non_qmaa_extn.xml \
    qms-saidl.xml \
    vendor.qti.diag.hal.service.xml \
    vendor.qti.gnss-service.xml \
    vendor.qti.hardware.perf2.xml \
    vendor.qti.hardware.qseecom@1.0-service.xml \
    vendor.qti.hardware.trustedui-aidl-service.xml \
    vendor.qti.qccvndhal_aidl-service.xml \
    vendor.samsung.hardware.radio_manifest_2_34.xml \
    vendor.samsung.hardware.sehradio_manifest_2_34.xml \
    ATFWD-daemon \
    adpl \
    adsprpcd \
    audioadsprpcd \
    cdsprpcd \
    cnss-daemon \
    diag-router \
    dspservice \
    factory.ssc \
    hermesd \
    android.hardware.bluetooth@1.1-service-qti \
    android.hardware.gatekeeper-service \
    android.hardware.gnss-aidl-service-qti \
    android.hardware.security.keymint-service-qti \
    android.hardware.security.keymint-service-spu-qti \
    rild \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.display.color-service \
    vendor.qti.hardware.iop@2.0-service \
    vendor.qti.hardware.perf2-hal-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.secureprocessor@1.0 \
    vendor.qti.hardware.trustedui-aidl-service-qti \
    vendor.qti.hardware.trustedui@1.0-service-qti \
    init.kernel.post_boot-pineapple \
    init.kernel.post_boot \
    init.qcom.class_core \
    init.qti.kernel \
    init.qti.media \
    init.qti.qcv \
    init.qti.time.daemon \
    init.qti.write \
    irsc_util \
    loadalgo \
    loc_launcher \
    lowi-server \
    pd-mapper \
    pm-proxy \
    pm-service \
    ppd \
    qcc-vendor \
    qcom-system-daemon \
    qdcmss \
    qms \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    qwesd \
    rmt_storage \
    sec_nvm \
    shsusrd \
    spdaemon \
    sscrpcd \
    ssgtzd \
    ssr_diag \
    ssr_setup \
    subsystem_ramdump \
    system_dlkm_modprobe \
    tftp_server \
    time_daemon \
    tlpd \
    trusteduilistener \
    ubwcconvert \
    vendor_modprobe \
    xtra-daemon

PRODUCT_PACKAGES += \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so
